### ISSUE TITLE
Update for scala 2.13

### ISSUE THREAD

**Issue by tomerghelber** [leobenkel/safety_plugin#37]
Hello,

I wanted to know if safety-plugin will have a version for scala 2.13.
I know that scalafix need to be updated to support but maybe there is more work around it.

Thanks.

**Comment by leobenkel** [comment]
Yes I can work on it. I'll put it on my list. If you have time, you can open a PR as well :) 

But I don't think the Scala version matter since it is a SBT plugin. Only the SBT version needs to align with your project. I think ? 

What is your use case ?

**Comment by tomerghelber** [comment]
Well, I tried to update a project to use scala 2.13, and got an error that semanticdb is not found. It is used by scalafix. It is weird that sbt plugin is depended on the project's scala. Maybe something is broken on my side. Anyway, updating is a good practice anyway so I asked.

**Comment by leobenkel** [comment]
ah thanks ! I will look into it !

**Comment by leobenkel** [comment]
@tomerghelber I made an update to attempt to fix the issue. Could you test it on your end ? if that resolve the problem you were encountering. 

There should be a public snapshot published:
```
[info] 	published safety_plugin to https://oss.sonatype.org/content/repositories/snapshots/com/leobenkel/safety_plugin_2.12_1.0/0.1.3+9-fd0ea554-SNAPSHOT/safety_plugin-0.1.3+9-fd0ea554-SNAPSHOT.jar
```

**Comment by leobenkel** [comment]
```
"com.leobenkel" % "safety_plugin" % "0.1.3+9-fd0ea554-SNAPSHOT"
```

**Comment by tomerghelber** [comment]
Made [a branch for scala 2.13](https://github.com/tomerghelber/mathematica-scala-parser-combinators/tree/feature/scala-2.13). Couldn't find it in the standard repository, how to add it?

**Comment by leobenkel** [comment]
I verified that it works in your project, you can add 
```
resolvers += Resolver.sonatypeRepo("snapshot")
```
to get the snapshot version, or wait for the [deploy](https://travis-ci.com/leobenkel/safety_plugin/builds/140162276) to complete. Then you will be able to use `0.1.5` as the new version. 

please let me know when it works on your end :)

**Comment by leobenkel** [comment]
Just doubled-checked after the deploy completed, `0.1.5` works fine ! :D
